"""add_conversation_content_and_model_fields_to_projects

Revision ID: 094490142390
Revises: 
Create Date: 2025-11-11 16:08:44.597387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '094490142390'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    说明：生产环境曾出现手工补字段的情况；为避免 `DuplicateColumn` 导致迁移中断，
    这里对每个字段做“存在即跳过”的幂等处理。
    """

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {c['name'] for c in inspector.get_columns('projects')}

    if 'conversation_content' not in existing_columns:
        op.add_column(
            'projects',
            sa.Column('conversation_content', sa.Text(), nullable=True),
        )
    if 'image_model' not in existing_columns:
        op.add_column(
            'projects',
            sa.Column('image_model', sa.String(length=100), nullable=True),
        )
    if 'aspect_ratio' not in existing_columns:
        op.add_column(
            'projects',
            sa.Column('aspect_ratio', sa.String(length=50), nullable=True),
        )
    if 'quality' not in existing_columns:
        op.add_column(
            'projects',
            sa.Column('quality', sa.String(length=50), nullable=True),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'quality')
    op.drop_column('projects', 'aspect_ratio')
    op.drop_column('projects', 'image_model')
    op.drop_column('projects', 'conversation_content')
    # ### end Alembic commands ###

